<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('provincias', function (Blueprint $table) {
            $table->id();
            $table->string('nombre', 100);
            $table->foreignId('departamento_id')->constrained('departamentos')->onDelete('cascade');
            $table->boolean('activo')->default(true);
            $table->timestamps();
        });

        DB::table('provincias')->insert([
            ['nombre' => 'CHACHAPOYAS', 'departamento_id' => 1, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'BAGUA', 'departamento_id' => 1, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'BONGARA', 'departamento_id' => 1, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CONDORCANQUI', 'departamento_id' => 1, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'LUYA', 'departamento_id' => 1, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'RODRIGUEZ DE MENDOZA', 'departamento_id' => 1, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'UTCUBAMBA', 'departamento_id' => 1, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'HUARAZ', 'departamento_id' => 2, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'AIJA', 'departamento_id' => 2, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'ANTONIO RAYMONDI', 'departamento_id' => 2, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'ASUNCION', 'departamento_id' => 2, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'BOLOGNESI', 'departamento_id' => 2, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CARHUAZ', 'departamento_id' => 2, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CARLOS FERMIN FITZCARRALD', 'departamento_id' => 2, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CASMA', 'departamento_id' => 2, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CORONGO', 'departamento_id' => 2, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'HUARI', 'departamento_id' => 2, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'HUARMEY', 'departamento_id' => 2, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'HUAYLAS', 'departamento_id' => 2, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'MARISCAL LUZURIAGA', 'departamento_id' => 2, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'OCROS', 'departamento_id' => 2, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'PALLASCA', 'departamento_id' => 2, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'POMABAMBA', 'departamento_id' => 2, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'RECUAY', 'departamento_id' => 2, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'SANTA', 'departamento_id' => 2, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'SIHUAS', 'departamento_id' => 2, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'YUNGAY', 'departamento_id' => 2, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'ABANCAY', 'departamento_id' => 3, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'ANDAHUAYLAS', 'departamento_id' => 3, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'ANTABAMBA', 'departamento_id' => 3, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'AYMARAES', 'departamento_id' => 3, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'COTABAMBAS', 'departamento_id' => 3, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CHINCHEROS', 'departamento_id' => 3, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'GRAU', 'departamento_id' => 3, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'AREQUIPA', 'departamento_id' => 4, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CAMANA', 'departamento_id' => 4, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CARAVELI', 'departamento_id' => 4, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CASTILLA', 'departamento_id' => 4, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CAYLLOMA', 'departamento_id' => 4, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CONDESUYOS', 'departamento_id' => 4, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'ISLAY', 'departamento_id' => 4, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'LA UNION', 'departamento_id' => 4, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'HUAMANGA', 'departamento_id' => 5, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CANGALLO', 'departamento_id' => 5, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'HUANCA SANCOS', 'departamento_id' => 5, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'HUANTA', 'departamento_id' => 5, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'LA MAR', 'departamento_id' => 5, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'LUCANAS', 'departamento_id' => 5, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'PARINACOCHAS', 'departamento_id' => 5, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'PAUCAR DEL SARA SARA', 'departamento_id' => 5, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'SUCRE', 'departamento_id' => 5, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'VICTOR FAJARDO', 'departamento_id' => 5, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'VILCAS HUAMAN', 'departamento_id' => 5, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CAJAMARCA', 'departamento_id' => 6, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CAJABAMBA', 'departamento_id' => 6, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CELENDIN', 'departamento_id' => 6, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CHOTA ', 'departamento_id' => 6, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CONTUMAZA', 'departamento_id' => 6, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CUTERVO', 'departamento_id' => 6, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'HUALGAYOC', 'departamento_id' => 6, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'JAEN', 'departamento_id' => 6, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'SAN IGNACIO', 'departamento_id' => 6, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'SAN MARCOS', 'departamento_id' => 6, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'SANTA MIGUEL', 'departamento_id' => 6, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'SAN PABLO', 'departamento_id' => 6, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'SANTA CRUZ', 'departamento_id' => 6, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CALLAO', 'departamento_id' => 7, 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CUSCO', 'departamento_id' => 8, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'ACOMAYO', 'departamento_id' => 8, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'ANTA', 'departamento_id' => 8, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CALCA', 'departamento_id' => 8, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CANAS', 'departamento_id' => 8, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CANCHIS', 'departamento_id' => 8, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CHUMBIVILCAS', 'departamento_id' => 8, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'ESPINAR', 'departamento_id' => 8, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'LA CONVENCION', 'departamento_id' => 8, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'PARURO', 'departamento_id' => 8, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'PAUCARTAMBO', 'departamento_id' => 8, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'QUISPICANCHI', 'departamento_id' => 8, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'URUBAMBA', 'departamento_id' => 8, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'HUANCAVELICA', 'departamento_id' => 9, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'ACOBAMBA', 'departamento_id' => 9, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'ANGARAES', 'departamento_id' => 9, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CASTROVIRREYNA', 'departamento_id' => 9, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CHURCAMPA', 'departamento_id' => 9, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'HUAYTARA', 'departamento_id' => 9, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'TAYACAJA', 'departamento_id' => 9, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'HUANUCO', 'departamento_id' => 10, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'AMBO', 'departamento_id' => 10, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'DOS DE MAYO', 'departamento_id' => 10, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'HUACAYBAMBA', 'departamento_id' => 10, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'HUAMALIES', 'departamento_id' => 10, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'LEONCIO PRADO', 'departamento_id' => 10, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'MARAÑON', 'departamento_id' => 10, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'PACHITEA', 'departamento_id' => 10, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'PUERTO INCA', 'departamento_id' => 10, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'LAURICOCHA', 'departamento_id' => 10, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'YAROWILCA', 'departamento_id' => 10, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'ICA', 'departamento_id' => 11, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CHINCHA', 'departamento_id' => 11, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'NAZCA', 'departamento_id' => 11, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'PALPA', 'departamento_id' => 11, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'PISCO', 'departamento_id' => 11, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'HUANCAYO', 'departamento_id' => 12, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CONCEPCION', 'departamento_id' => 12, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CHANCHAMAYO', 'departamento_id' => 12, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'JAUJA', 'departamento_id' => 12, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'JUNIN', 'departamento_id' => 12, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'SATIPO', 'departamento_id' => 12, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'TARMA', 'departamento_id' => 12, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'YAULI', 'departamento_id' => 12, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CHUPACA', 'departamento_id' => 12, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'TRUJILLO', 'departamento_id' => 13, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'ASCOPE', 'departamento_id' => 13, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'BOLIVAR', 'departamento_id' => 13, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CHEPEN', 'departamento_id' => 13, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'JULCAN', 'departamento_id' => 13, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'OTUZCO', 'departamento_id' => 13, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'PACASMAYO', 'departamento_id' => 13, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'PATAZ', 'departamento_id' => 13, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'SANCHEZ CARRION', 'departamento_id' => 13, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'SANTIAGO DE CHUCO', 'departamento_id' => 13, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'GRAN CHIMU', 'departamento_id' => 13, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'VIRU', 'departamento_id' => 13, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CHICLAYO', 'departamento_id' => 14, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'FERREÑAFE', 'departamento_id' => 14, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'LAMBAYEQUE', 'departamento_id' => 14, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'LIMA', 'departamento_id' => 15, 'activo' => true, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'BARRANCA', 'departamento_id' => 15, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CAJATAMBO', 'departamento_id' => 15, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CANTA', 'departamento_id' => 15, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CAÑETE', 'departamento_id' => 15, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'HUARAL', 'departamento_id' => 15, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'HUAROCHIRI', 'departamento_id' => 15, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'HUAURA', 'departamento_id' => 15, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'OYON', 'departamento_id' => 15, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'YAUYOS', 'departamento_id' => 15, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'MAYNAS', 'departamento_id' => 16, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'ALTO AMAZONAS', 'departamento_id' => 16, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'LORETO', 'departamento_id' => 16, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'MARISCAL RAMON CASTILLA', 'departamento_id' => 16, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'REQUENA', 'departamento_id' => 16, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'UCAYALI', 'departamento_id' => 16, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'TAMBOPATA', 'departamento_id' => 17, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'MANU', 'departamento_id' => 17, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'TAHUAMANU', 'departamento_id' => 17, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'MARISCAL NIETO', 'departamento_id' => 18, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'GENERAL SANCHEZ CERRO', 'departamento_id' => 18, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'ILO', 'departamento_id' => 18, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'PASCO', 'departamento_id' => 19, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'DANIEL ALCIDES CARRION', 'departamento_id' => 19, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'OXAPAMPA', 'departamento_id' => 19, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'PIURA', 'departamento_id' => 20, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'AYABACA', 'departamento_id' => 20, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'HUANCABAMBA', 'departamento_id' => 20, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'MORROPON', 'departamento_id' => 20, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'PAITA', 'departamento_id' => 20, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'SULLANA', 'departamento_id' => 20, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'TALARA', 'departamento_id' => 20, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'SECHURA', 'departamento_id' => 20, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'PUNO', 'departamento_id' => 21, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'AZANGARO', 'departamento_id' => 21, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CARABAYA', 'departamento_id' => 21, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CHUCUITO', 'departamento_id' => 21, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'EL COLLAO', 'departamento_id' => 21, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'HUANCANE', 'departamento_id' => 21, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'LAMPA', 'departamento_id' => 21, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'MELGAR', 'departamento_id' => 21, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'MOHO', 'departamento_id' => 21, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'SAN ANTONIO DE PUTINA', 'departamento_id' => 21, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'SAN ROMAN', 'departamento_id' => 21, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'SANDIA', 'departamento_id' => 21, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'YUNGUYO', 'departamento_id' => 21, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'MOYOBAMBA', 'departamento_id' => 22, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'BELLAVISTA', 'departamento_id' => 22, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'EL DORADO', 'departamento_id' => 22, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'HUALLAGA', 'departamento_id' => 22, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'LAMAS', 'departamento_id' => 22, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'MARISCAL CACERES', 'departamento_id' => 22, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'PICOTA', 'departamento_id' => 22, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'RIOJA', 'departamento_id' => 22, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'SAN MARTIN', 'departamento_id' => 22, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'TOCACHE', 'departamento_id' => 22, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'TACNA', 'departamento_id' => 23, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CANDARAVE', 'departamento_id' => 23, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'JORGE BASADRE', 'departamento_id' => 23, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'TARATA', 'departamento_id' => 23, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'TUMBES', 'departamento_id' => 24, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CONTRALMIRANTE VILLAR', 'departamento_id' => 24, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'ZARUMILLA', 'departamento_id' => 24, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'CORONEL PORTILLO', 'departamento_id' => 25, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'ATALAYA', 'departamento_id' => 25, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'PADRE ABAD', 'departamento_id' => 25, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'PURUS', 'departamento_id' => 25, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'DATEM DEL MARAÑON', 'departamento_id' => 16, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
            ['nombre' => 'PUTUMAYO', 'departamento_id' => 16, 'activo' => false, 'created_at' => now(), 'updated_at' => now()],
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('provincias');
    }
};